# Use Travis' Docker infrastructure
sudo: false

language: ruby
rvm: 2.2

cache: bundler
env: BUNDLE_PATH=bundle-vendor/bundle

# Override to force using .bundle/config
install:
- bundle install

script:
- bundle exec jekyll build
