# Dependencies

# We use kramdown for TOC generation.
# See http://www.seanbuscay.com/blog/jekyll-toc-markdown for details:
markdown:         kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            ENSIME
description:      '<b>EN</b>hanced <b>S</b>cala &amp; java <b>I</b>nteraction <b>M</b>ode for text <b>E</b>ditors'
baseurl:          /

#exclude: [talks]
exclude: [bundle-vendor]

gems:
  - jekyll-sitemap
