# Dependencies
markdown:         kramdown
highlighter:      pygments

kramdown:
  input: GFM

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ENSIME
description:      'ENhanced Scala and java Interaction Mode for text Editors'
baseurl:          /

exclude: [talks]

