# Dependencies
markdown:         redcarpet
highlighter:      pygments

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ENSIME
description:      'ENhanced Scala and java Interaction Mode for text Editors'
baseurl:          /

#exclude: [talks]
exclude: [bundle-vendor]

gems:
  - jekyll-sitemap
