# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ENSIME
description:      'ENhanced Scala and java Interaction Mode for text Editors'
baseurl:          /

exclude: [talks]

